goapp.idejercicio = 1100000016
goapp.terminal = 8
goapp.idusuario = 1
goapp.sucursal = 1
goapp.switchusuario = '11000'
goapp.ejercicio = 6
oavisar.usuario('goapp.idejercicio = '+LTRIM(STR(goapp.idejercicio))+CHR(13);
				+'GOAPP.SUCURSAL10 = '+STR(GOAPP.SUCURSAL10)+CHR(13);
				+'Goapp.terminal =' + STR(goapp.terminal))